# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      PASS: dummy

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: workflow command
        run: | 
            echo "::error file=test.sh,line=5::test failed"
            echo "::group::My title"
            echo "Inside group"
            echo "::endgroup::"
            echo "::add-mask::$PASS"
            echo "pass: $PASS"
            echo "::add-mask::himitsu"
            echo "pass: himitsu"
  prompt:
    runs-on: ubuntu-latest
    steps:
      - name: apt install
        run: sudo apt install jq
  
  progress-bar:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: docker pull
        run: docker pull screwdrivercd/screwdriver
      - name: creat file
        run: dd if=/dev/urandom of=./bigfile bs=$((1024*1024)) count=1024
      - name: curl
        run:  curl --progress-bar -o /tmp/bigfile file://$(pwd)/bigfile
